/* GastricCancerDetection Phase 1 additive schema. Database-first: run manually against gastriccancerdb. */
IF SCHEMA_ID('ref') IS NULL EXEC('CREATE SCHEMA ref');
IF SCHEMA_ID('geno') IS NULL EXEC('CREATE SCHEMA geno');
IF SCHEMA_ID('analysis') IS NULL EXEC('CREATE SCHEMA analysis');
GO
IF COL_LENGTH('analysis.AnalysisRuns','Dataset') IS NULL ALTER TABLE analysis.AnalysisRuns ADD Dataset nvarchar(200) NULL;
IF COL_LENGTH('analysis.AnalysisRuns','GenomeBuild') IS NULL ALTER TABLE analysis.AnalysisRuns ADD GenomeBuild nvarchar(50) NULL;
IF COL_LENGTH('analysis.AnalysisRuns','PythonVersion') IS NULL ALTER TABLE analysis.AnalysisRuns ADD PythonVersion nvarchar(50) NULL;
IF COL_LENGTH('analysis.AnalysisRuns','Parameters') IS NULL ALTER TABLE analysis.AnalysisRuns ADD Parameters nvarchar(max) NULL;
IF COL_LENGTH('analysis.AnalysisRuns','StartTime') IS NULL ALTER TABLE analysis.AnalysisRuns ADD StartTime datetime2 NULL;
IF COL_LENGTH('analysis.AnalysisRuns','EndTime') IS NULL ALTER TABLE analysis.AnalysisRuns ADD EndTime datetime2 NULL;
IF COL_LENGTH('analysis.AnalysisRuns','ErrorMessage') IS NULL ALTER TABLE analysis.AnalysisRuns ADD ErrorMessage nvarchar(max) NULL;
GO
IF OBJECT_ID('analysis.ModelVersions') IS NULL CREATE TABLE analysis.ModelVersions(ModelVersionId int IDENTITY PRIMARY KEY,VersionName nvarchar(100) NOT NULL UNIQUE,PipelineVersion nvarchar(100) NOT NULL,Description nvarchar(1000) NULL,ParametersJson nvarchar(max) NOT NULL DEFAULT '{}',IsActive bit NOT NULL DEFAULT 1,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ref.RegulatoryElements') IS NULL CREATE TABLE ref.RegulatoryElements(RegulatoryElementId bigint IDENTITY PRIMARY KEY,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Start bigint NOT NULL,[End] bigint NOT NULL,ElementType nvarchar(50) NOT NULL,Source nvarchar(100) NULL,ElementId nvarchar(200) NULL,Gene nvarchar(200) NULL,Annotation nvarchar(1000) NULL);
IF OBJECT_ID('ref.RepeatElements') IS NULL CREATE TABLE ref.RepeatElements(RepeatElementId bigint IDENTITY PRIMARY KEY,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Start bigint NOT NULL,[End] bigint NOT NULL,RepeatType nvarchar(50) NOT NULL,Family nvarchar(100) NULL,ElementId nvarchar(200) NULL);
IF OBJECT_ID('ref.PMDRegions') IS NULL CREATE TABLE ref.PMDRegions(PMDRegionId bigint IDENTITY PRIMARY KEY,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Start bigint NOT NULL,[End] bigint NOT NULL,LengthBp bigint NOT NULL,Source nvarchar(100) NULL);
IF OBJECT_ID('ref.MitoRegions') IS NULL CREATE TABLE ref.MitoRegions(MitoRegionId bigint IDENTITY PRIMARY KEY,RegionName nvarchar(200) NOT NULL,Start bigint NOT NULL,[End] bigint NOT NULL,FeatureType nvarchar(100) NULL);
IF OBJECT_ID('geno.NonCodingVariants') IS NULL CREATE TABLE geno.NonCodingVariants(NonCodingVariantId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Position bigint NOT NULL,RefAllele nvarchar(500) NOT NULL,AltAllele nvarchar(500) NOT NULL,Gene nvarchar(200) NULL,Region nvarchar(100) NULL,FunctionalClass nvarchar(100) NULL,Vaf float NULL,Recurrence int NULL,IsGermline bit NULL,PopulationFrequency float NULL,RegulatoryAnnotation nvarchar(1000) NULL,CohortCount int NOT NULL DEFAULT 0,IndependentCohortCount int NOT NULL DEFAULT 0,ValidationCount int NOT NULL DEFAULT 0,Subtype nvarchar(100) NULL,Stage nvarchar(50) NULL,DiagnosticEvidence nvarchar(1000) NULL,LiteratureStatus nvarchar(100) NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('geno.CopyNumberAlterations') IS NULL CREATE TABLE geno.CopyNumberAlterations(CopyNumberAlterationId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Arm nvarchar(20) NULL,Start bigint NOT NULL,[End] bigint NOT NULL,SizeBp bigint NOT NULL,CopyNumber float NULL,TumorFrequency float NULL,NormalFrequency float NULL,CohortRecurrence float NULL,EventType nvarchar(50) NULL,Subtype nvarchar(100) NULL,Stage nvarchar(50) NULL,Validation nvarchar(1000) NULL,LiteratureEvidence nvarchar(1000) NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('geno.MitoVariants') IS NULL CREATE TABLE geno.MitoVariants(MitoVariantId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,Position bigint NOT NULL,RefAllele nvarchar(100) NOT NULL,AltAllele nvarchar(100) NOT NULL,Depth int NULL,Vaf float NULL,Heteroplasmy float NULL,PopulationFrequency float NULL,Haplogroup nvarchar(100) NULL,CopyNumber float NULL);
IF OBJECT_ID('geno.MethylationCall') IS NULL CREATE TABLE geno.MethylationCall(MethylationCallId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Position bigint NOT NULL,BetaValue float NULL,Coverage float NULL,SampleType nvarchar(100) NULL);
IF OBJECT_ID('geno.MethylationRegion') IS NULL CREATE TABLE geno.MethylationRegion(MethylationRegionId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,BuildId int NOT NULL,Chromosome nvarchar(30) NOT NULL,Start bigint NOT NULL,[End] bigint NOT NULL,MeanMethylation float NULL,TumorNormalDelta float NULL,RegionType nvarchar(100) NULL,CohortCount int NULL,ValidationCount int NULL,LiteratureStatus nvarchar(100) NULL);
IF OBJECT_ID('analysis.Candidates') IS NULL CREATE TABLE analysis.Candidates(CandidateId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,ModelVersionId int NULL,CandidateKey nvarchar(300) NOT NULL,CandidateName nvarchar(300) NULL,FeatureType nvarchar(100) NOT NULL,Chromosome nvarchar(30) NULL,Start bigint NULL,[End] bigint NULL,RegionSizeBp bigint NULL,TumorEffect nvarchar(1000) NULL,StatisticalRobustness float NULL,BiologicalEvidence float NULL,LiteratureWhitespace float NULL,ValidationGap float NULL,EarlyStageScore float NULL,CancerSpecificityScore float NULL,CfDNADetectabilityScore float NULL,OverallPriority float NULL,EvidenceStatus nvarchar(100) NOT NULL DEFAULT 'Insufficient Evidence',CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Candidates_Run_Key UNIQUE(AnalysisRunId,CandidateKey));
IF OBJECT_ID('analysis.CandidateEvidence') IS NULL CREATE TABLE analysis.CandidateEvidence(EvidenceId bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,EvidenceType nvarchar(100) NOT NULL,Source nvarchar(500) NULL,SourceIdentifier nvarchar(200) NULL,EvidenceLevel nvarchar(100) NULL,NumericValue float NULL,ValueText nvarchar(max) NULL,Notes nvarchar(max) NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.LiteratureEvidence') IS NULL CREATE TABLE analysis.LiteratureEvidence(LiteratureEvidenceId bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,PaperCount int NOT NULL DEFAULT 0,StudyCount int NOT NULL DEFAULT 0,CohortCount int NOT NULL DEFAULT 0,IndependentCohortCount int NOT NULL DEFAULT 0,ExternalValidationCount int NOT NULL DEFAULT 0,MulticenterCount int NOT NULL DEFAULT 0,StageICount int NOT NULL DEFAULT 0,StageIICount int NOT NULL DEFAULT 0,BenignControlCount int NOT NULL DEFAULT 0,OtherCancerControlCount int NOT NULL DEFAULT 0,AssayCount int NOT NULL DEFAULT 0,FirstYear int NULL,LatestYear int NULL,LiteratureSaturationIndex float NULL,LiteratureWhitespaceIndex float NULL,ValidationGapScore float NULL,WhitespaceClass nvarchar(100) NOT NULL DEFAULT 'Insufficient Evidence',EvidenceNotes nvarchar(max) NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.WhitespaceScores') IS NULL CREATE TABLE analysis.WhitespaceScores(Id bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,SaturationIndex float NOT NULL,WhitespaceIndex float NOT NULL,Classification nvarchar(100) NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.ValidationGapScores') IS NULL CREATE TABLE analysis.ValidationGapScores(Id bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,Score float NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.EarlyStageScores') IS NULL CREATE TABLE analysis.EarlyStageScores(Id bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,StageI float NOT NULL,StageII float NOT NULL,Precursor float NOT NULL,LowTumorBurden float NOT NULL,CfDNARelevance float NOT NULL,Score float NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.CancerSpecificityScores') IS NULL CREATE TABLE analysis.CancerSpecificityScores(Id bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,Healthy float NOT NULL,BenignGastric float NOT NULL,OtherCancer float NOT NULL,Score float NOT NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.CfDNADetectabilityScores') IS NULL CREATE TABLE analysis.CfDNADetectabilityScores(Id bigint IDENTITY PRIMARY KEY,CandidateId bigint NOT NULL,AnalysisRunId int NOT NULL,RegionSizeBp bigint NULL,InformativeSiteCount int NULL,SignalStrength float NULL,CopyMultiplier float NULL,DilutionResistance float NULL,LowDepthFeasibility float NULL,RegionalRedundancy float NULL,EarlyStageScore float NULL,CancerSpecificityScore float NULL,LiteratureWhitespace float NULL,ValidationGap float NULL,BiologicalSupport float NULL,TechnicalFeasibility float NULL,CfDNADetectabilityScoreValue float NULL,ModelVersion nvarchar(100) NULL,CreatedAt datetime2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('analysis.IntegratedPanels') IS NULL CREATE TABLE analysis.IntegratedPanels(IntegratedPanelId bigint IDENTITY PRIMARY KEY,AnalysisRunId int NOT NULL,PanelName nvarchar(200) NOT NULL,FeatureSetJson nvarchar(max) NULL,Score float NULL,Status nvarchar(100) NULL);
GO

/*
Default candidate priority formula (configurable; not a clinical model):
0.20 Biological Evidence
+0.15 Statistical Robustness
+0.15 Literature Whitespace
+0.15 Validation Gap
+0.15 Early-stage Relevance
+0.10 GC Specificity
+0.10 cfDNA Detectability
All components are expected on [0,1]. Missing evidence remains NULL and must not be silently interpreted as clinical evidence.
*/
